export {
	BUILTIN_DOMAIN_PLUGIN_ADMISSIONS,
	DEFAULT_DOMAIN_REGISTRY,
	SOFTWARE_DEVELOPMENT_DOMAIN_IDENTITY as DEFAULT_DOMAIN_PLUGIN_IDENTITY,
	SOFTWARE_DEVELOPMENT_DOMAIN_PLUGIN as DEFAULT_DOMAIN_PLUGIN_ADMISSION,
} from "./software-development/plugin.ts";
